### ISSUE TITLE
Clean up org teams

### ISSUE THREAD

**Issue by Vinai** [mage-os/terraform#16]
<img width="999" alt="Bildschirm­foto 2022-11-06 um 10 44 06" src="https://user-images.githubusercontent.com/72463/200192009-26f0567a-44da-420b-8e8d-bf02778b5bc5.png">

**Comment by sprankhub** [comment]
I deleted all teams without members. Now it looks much better:

![image](https://github.com/mage-os/terraform/assets/930199/935013c5-3955-4369-8998-b09a25bac659)

I think we can / should also delete "Continious Integration" and "Continuous Integration" as these are not managed through Terraform. @IvanChepurnyi, any objections since you are part of one of these teams?

Afterwards, we should improve the description of the teams here: https://github.com/mage-os/terraform/blob/e9e0eda0e1665aa8a2e553d9f7e24f2bae00eec7/variables.tf#L136-L185

**Comment by IvanChepurnyi** [comment]
@sprankhub I do not mind as soon as it doesn't cut my access from org.

**Comment by sprankhub** [comment]
The only teams left now are the ones added through Terraform:

https://github.com/mage-os/terraform/blob/5ec3e68f643f5f2b51d73ef667487d1095c9424b/variables.tf#L136-L193
